### ISSUE TITLE
Add the ability to track events from different agents

### ISSUE THREAD

**Issue by fforbeck** [storacha/elizaos-adapter#48]
Whenever we ship new integrations, features, or products, we see overall growth in users and uploads, but we can't pinpoint exactly what's driving adoption.

It would be great to track what's working. One idea suggested by @alanshaw  is to update the ucanto library allowing custom headers during server connections.

With that in place, we can update the Storacha client to support these headers when creating an agent. Each integration can then pass something like `X-Client: "storacha/mcp-v1"`, giving us clear analytics on what's performing best—and helping us decide where to double down or pivot next.

**Comment by alanshaw** [comment]
Specifically the ability to add custom HTTP headers to the Ucanto HTTP transport. This should be _super_ easy.

I suggest we include the client language and version (perhaps major version is fine), so we can tell which languages are driving most traffic and also when we can deprecate features because users have switched to newer clients.

So perhaps something more like a user agent string:

```yml
# JS client v1 running in the browser 
X-Client: Storacha/1 (js; Browser)

# Go client v1
X-Client: Storacha/1 (go)

# JS client v1 running in Node.js instantiated by MCP server integration.
X-Client: Storacha/1 (js; Node.js) MCP/1
```
